### ISSUE TITLE
Consider alternative to fh.sync (possibly websocket based)

### ISSUE THREAD

**Issue by TinyExplosions** [feedhenry-raincatcher/raincatcher-core#79]
Consider alternative to fh.sync (possibly websocket based)

**Comment by TinyExplosions** [comment]
At the moment, the fh.sync engine is solely long polling based, and given the shift in web technologies etc, is it time to reexamine the usefulness of this approach. It seems that in general, collisions would be rare in RainCatcher, as mostly people will be working on their own chunks of data, so is a whole sync engine required.

Something with a good, fast CRUD api, and websockets (even broadcast only to begin with, but trivial to add user-specific ones too) would enable a huge amount of flexibility, and if it has a clear audit trail built in, it can even help resolve any collisions that may happen infrequently.

Worth a bit of consideration at least

**Comment by wtrocki** [comment]
@TinyExplosions Thanks for suggestion. With new RainCatcher we have ability to replace sync with any other framework by just extending another interface. 
I think we will need to spike some simplified synchronization mechanisms using web sockets.

Suggested feature set may be similar to: https://www.twilio.com/sync

**Comment by wei-lee** [comment]
@TinyExplosions it is something we want to support in `fh.sync`. Feel free to submit proposals to fh-sync!

**Comment by wtrocki** [comment]
Moving possible suggestions to sync repository. Closing as RainCatcher is only using sync.
